### ISSUE TITLE
Could you let me know the values in graph or indicate the exact numbers in your paper? 

### ISSUE THREAD

**Issue by EthanCalvin** [sacmehta/ESPNet#1]
Hi, I read your paper and want to know exact values in your graph in Figures 5,6,7. 
Could you let me know the values in graph or indicate the exact numbers in your paper?

**Comment by sacmehta** [comment]
See Table 2 for exact values of our module ESP.

**Comment by sacmehta** [comment]
Table 2 contains the accuracy and model size. Other values are hardware deprendent and you should be able to reproduce them with the source code.

**Comment by EthanCalvin** [comment]
Thank you for your quick reply, I need to reproduce other values with my hardware. but If you don't mind could I ask inference time for each model?

**Comment by sacmehta** [comment]
As I mentioned, these values are hardware dependent. If you have exact hardware (e.g. laptop) as listed in Appendix, you should get 112 fps for a resolution of 1024x512.

You need to reproduce values for other models yourself. Please note that we didn’t use CRF with any models while computing inference speed, so FPS will drop further if you are using CRF.

Please use this space for any code related issues.
