### ISSUE TITLE
The operation of a neural network on a single board computer (Raspberry, Odroid etc.)

### ISSUE THREAD

**Issue by DenisN03** [sacmehta/ESPNet#16]
Hello, @sacmehta!
I've one more question.
Have you tried to run your neural network architecture on embedded platforms? Under the embedded platform, I mean Raspberry Pi, Orange Pi, Odroid and others. If so, what results did you get on the speed of work (FPS)? If you did not run, why? Do you think this neural network will work on these platforms? If so, how do I run ESPNet on such a platform?
At the moment, I managed to run ENet on a single-board Odroid computer, the speed of work was 3 FPS. I'm counting on the fact that your architecture will work faster. Thank you!

**Comment by sacmehta** [comment]
I have not tried running on these platforms, but any architecture should work.

Instead of using a PyTorch, you should use Caffe2 which is much more optimized. See below link for more details.

https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html

**Comment by DenisN03** [comment]
I compiled Pytorch 0.3.0 on a single-board computer. When trying to start test of a neural network, an error occurs:
`AssertionError: Torch not compiled with CUDA enabled`
When I run test the gpu parameter was set to False. Is it necessary to use pytorch version 0.3.0 or newer versions, too, should work?

**Comment by engineer1109** [comment]
@DenisN03 Seem you don’t use cuda pytorch
