### ISSUE TITLE
different Model.py in train and test

### ISSUE THREAD

**Issue by heumchri** [sacmehta/ESPNet#17]
Hi, 

after training a model on my own, I noticed that I could not perform inference with the scripts provided. 
This is the case because the Model.py in the test and train folder are different.
train: 
line 339: `self.conv = CBR(19 + classes, classes, 3, 1)`
line 382:  `concat_features = self.conv(torch.cat([comb_l2_l3, output0_cat], 1))`
test: 
line 339: `self.conv = CBR(16 + classes, classes, 3, 1)`
line 382:  `concat_features = self.conv(torch.cat([comb_l2_l3, output0], 1))`

Since the version in the test folder works with the provided pretrained models, I assume that this is the correct version?

**Comment by sacmehta** [comment]
See https://github.com/sacmehta/ESPNet/issues/14
