### ISSUE TITLE
training details

### ISSUE THREAD

**Issue by lizhengwei1992** [sacmehta/ESPNet#18]
hi, @sacmehta!
I see that in the paper:
__First, ESPNet-C was trained with down-sampled annotations. Second, a light-weight decoder was attached to ESPNet-C and then, the entire ESPNet network was trained__    

you freeze the parameters of encoder(ESPNet-C ) in the  training of ESPNet ?

**Comment by sacmehta** [comment]
No, we do not freeze the weights.
