### ISSUE TITLE
Amount of FLOPs for ESP module

### ISSUE THREAD

**Issue by bloonz** [sacmehta/ESPNet#20]
Hello @sacmehta,
thank you for your work. 
I was wondering how much FLOPs does an ESP module require.

**Comment by sacmehta** [comment]
We didn’t compute FLOPs. However, it is straightforward to compute them.

**Comment by msson** [comment]
@bloonz @sacmehta 
Did you figure out how to compute FLOPs for ESPNet? I am trying but it is not that straightforward for me.

**Comment by sacmehta** [comment]
@msson 
Check this code: https://github.com/warmspringwinds/pytorch-segmentation-detection/blob/master/pytorch_segmentation_detection/utils/flops_benchmark.py
