### ISSUE TITLE
PSPNet conversion

### ISSUE THREAD

**Issue by iliadsouti** [sacmehta/ESPNet#24]
Hi,

Can you share your PSPNet conversion code (pretrained model)? It seems the pytorch model has lower performance than the caffe model.

**Comment by sacmehta** [comment]
Please check the correct repository. This repository is for ESPNet and not PSPNet

**Comment by iliadsouti** [comment]
From the paper "All networks (FCN-8s, SegNet, SQNet, ENet, DeepLabv2, PSPNet, and ERFNet were without conditional random field and converted to PyTorch for a fair comparison ".
Since PSPNet is in caffe, I'm wondering can you provide the Pytorch converted model that you used for comparison.
