### ISSUE TITLE
How to use the code 'IOUEval.py' in 'train' directory?

### ISSUE THREAD

**Issue by wangq95** [sacmehta/ESPNet#25]
The code 'IOUEval.py' defined the class of mIoU and per class iou calculation, and used in training procedure, but how to reuse this code for evaluating the predicted result? Thank you!

**Comment by sacmehta** [comment]
IOUEval file just need predicted segmentation mask and ground truth. If you have this information you can easily call the function inside IOUEval to compute mIOU
