### ISSUE TITLE
Why mIoU is lower than the result provided by the author? 

### ISSUE THREAD

**Issue by wangq95** [sacmehta/ESPNet#26]
I use the pretrained model provided by the author to evaluate the validation data (500 images) of cityscapes  dataset, and the mIoU result is only 54%, but the result provided by the author is 60% (on test data of cityscapes), will the gap be so big?

**Comment by sacmehta** [comment]
The scripts provided by the Cityscapes team for computing mIOU are different than ours. We don’t mask the background and unmarked areas while the CityScapes does. If you use their scripts, you should be able to get the reported accuracy.
