### ISSUE TITLE
There is a problem that ZeroDivisionError: float division by zero, how can I fix it?

### ISSUE THREAD

**Issue by ghost** [sacmehta/ESPNet#27]
When I run the code by classes=2, I initial the code  "    model = net.ESPNet(classes=2)"

**Comment by sacmehta** [comment]
see #13

**Comment by ghost** [comment]
> see #13

thanks for your help

**Comment by Ji-qing** [comment]
hi

**Comment by Jee-King** [comment]
Hi，could you give me some suggestions on  **_classes=2_**.

**Comment by ghost** [comment]
> Hi，could you give me some suggestions on **_classes=2_**.

you can initial your network with classes = 20, and add a conv layer to transpose 20 to 2 at the end.

**Comment by Jee-King** [comment]
Hi,
How about the effect?
I  did not get good results by changing the model.py in #13. The smallest train loss I got was 0.036.
Could you give me some suggestions? Thank you very much.
