### ISSUE TITLE
how to use GEMM & memory re-ordering

### ISSUE THREAD

**Issue by EthanCalvin** [sacmehta/ESPNet#3]
hi, I want to check comparison between state-of-the-art segmentation methods in Fig 6. your paper.

First, I am trying to implement erfnet code in pytorch on TX2 but i got stuck running program as  " RuntimeError: cuda runtime error (7) : too many resources requested for launch at /home...   src/ THCUNN/im2col.h"

your paper mentioned that using optimized general matrix multiplication(GEMM) & memory re-ordering operations such as im2col           /  How to use this opertaion.

**Comment by sacmehta** [comment]
This seems to be an issue with your PyTorch/CUDA/CUDNN installation and not with the code (ERFNet).

Please post these issues in  appropriate forums.
