### ISSUE TITLE
How to evaluate

### ISSUE THREAD

**Issue by userb2020** [sacmehta/ESPNet#31]
Hello.

I trained your ESPNet and want to evaluate the model(mIoU).
So, I made test/main.py using your train/main.py code.
However, I realized that I need test.txt file of cityscapes to run the code.
Is there anyway to get test.txt file of cityscapes?
Or can you let me know how can I check your model's mIoU?

Thanks.

**Comment by sacmehta** [comment]
i) Copy your model.py (should be the same file as you used for training) file from train folder to the test folder and the weights too. 
ii) Assuming you have all your validation (or test) images in ./data folder. Now, make changes to the arguments as required and run the Visualize*.py file.
iii) This would generate predictions for you depending upon your arguments in the results* folder. Rename that folder to result which you can use for evaluation.

P.S.: Output will be 1024x512, so upsample to 2048x1024 using nearest neighbor interpolation
