### ISSUE TITLE
The IoU calculation problem.

### ISSUE THREAD

**Issue by zhengxiawu** [sacmehta/ESPNet#33]
in line 41 of train/IOUEval.py

` self.batchCount += 1`

but in train/main.py, the batch size is 
`batch_size=args.batch_size + 4`

when I set batch_size = 1, the performance of decoder_2_8 on cityscape will drop to 37.05 and on camVid will drop to 44.89。
on camVid when batch size = 1 mIOU = 44.89.  batch size = 4 mIOU=45.9, batch size = 32 mIOU = 44.4

**Comment by sacmehta** [comment]
IOUEval should be independent of the provided batch size (via args) because it computes the batch size based on  the input and target matrices. Let me take a more closer look.

**Comment by zhengxiawu** [comment]
thanksa lot! (the provided network works fine with cityscape scripts, but lower when using IOUEval)would you please tell me how u evaluate the performance on camVid? on ioueval ?

**Comment by zhengxiawu** [comment]
I also have done more experiment on cityscape with ESPnet, i.e. batch_size=1, mIOU=37.05; batch_size=2,mIOU=40.7;batch_size=4,mIOU=43.9;

**Comment by sacmehta** [comment]
Could you share your procedure for computing mIOU at different batch sizes?
