### ISSUE TITLE
testing on unseen dataset (Mapillary)

### ISSUE THREAD

**Issue by shaoyuanlo** [sacmehta/ESPNet#35]
Hi,
In your paper, you conducted an experiment that trained ESPNet on Cityscapes but tested on Mapillary.
However, the number of classes is different between the two datasets.
How did you test and evaluate the mIoU?
Thanks.

**Comment by sacmehta** [comment]
1) We tested on category level and not at class level.
2) classes belonging to the same category are merged (e.g.: car and truck are merged to vehicle category)

**Comment by shaoyuanlo** [comment]
How did you get the category level labels?

**Comment by sacmehta** [comment]
You follow the same procedure as Cityscapes does.

**Comment by pkuqgg** [comment]
> How did you get the category level labels?

Hi!I am a student, do you have Mapillary data set?
Have you solved the label problems?
Hoping for your reply! Thanks!
