### ISSUE TITLE
Question about RuntimeError 

### ISSUE THREAD

**Issue by msson** [sacmehta/ESPNet#37]
Hi, 
I got this error below and I can't figure it out which part is wrong. (I also attached my parameters)
I've already run with 1024x768 size dataset using same parameter but when I resize my dataset to 512x384 then the error shows up. (I also changed the parameters width and height)
![2018-11-16 11-39-39](https://user-images.githubusercontent.com/35793913/48594547-5842bb00-e994-11e8-9f23-480bcdf11e8c.png)
![2018-11-16 11-36-45](https://user-images.githubusercontent.com/35793913/48594549-5973e800-e994-11e8-94e7-6487fc3f676f.png)

**Comment by msson** [comment]
I am wondering this is because the data augmentation parts.
![2018-11-16 11-50-36](https://user-images.githubusercontent.com/35793913/48594873-dbb0dc00-e995-11e8-9a3a-fc7544da57bb.png)

**Comment by sacmehta** [comment]
All parameters inside myTransforms.Scale should be divisible by 8. For example, 538 in trainDataset_scale2 is not divisible by 8. Please check all of them and it should help you resolve your error.

**Comment by msson** [comment]
Thanks a lot!
