### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by msson** [sacmehta/ESPNet#38]
Hi,
I tried to train my own dataset (4263 images and 4263 labeled images) and I've gotten this error below.

![2018-11-19 16-39-12](https://user-images.githubusercontent.com/35793913/48692534-b92ef500-ec19-11e8-9cbb-331beec0354d.png)

I do not know what the problem is.

Thanks.

**Comment by msson** [comment]
I already checked the number of images and also checked .txt files.

**Comment by sacmehta** [comment]
Could you please upload a small subset of your train.txt file?

**Comment by msson** [comment]
/trainIm/180824-161340CAM1_50__V___C_Rear.png,/trainAnnot/180824-161340CAM1_50__V___C_Rear_All_Grey.png
/trainIm/180824-161340CAM1_86__V___C_Rear.png,/trainAnnot/180824-161340CAM1_86__V___C_Rear_All_Grey.png

**Comment by msson** [comment]
I solved this problem it was because of input file format. (I use .png but found some .bmp files in the folder.)
