### ISSUE TITLE
EvaluationQuestions

### ISSUE THREAD

**Issue by lxtGH** [sacmehta/ESPNet#39]
Hi! Thanks for your paper. Your results are got from 1024 * 512 input images? right? What about the full images input speed and IOU??

**Comment by sacmehta** [comment]
We didn’t train and test at full image resolution. If you train at full resolution, you should see 1-2% improvement in mIOU with drop in FPS.

**Comment by lxtGH** [comment]
What is the speed of ESPnet at full resolution.
I test it using 1080TI and I got 49 fps at the end.
