### ISSUE TITLE
Question about CDilated(nn.Module)

### ISSUE THREAD

**Issue by userb2020** [sacmehta/ESPNet#40]
Hello.
Your paper is really interesting and impressing.
And I have a question about your network.
I changed CDilated class in Model.py to speed up the network.
I apply factorization to CDilated class.
To be specific I changed the code as follows

<img width="1125" alt="cdilated" src="https://user-images.githubusercontent.com/44260821/49353102-3a4cb880-f6ff-11e8-8ca0-884cc6d89275.png">

As far as I know, I learned that factorized convolution reduce the number of parameters and reduce the inference time. But, this changed network has 87 fps and your network has 146 fps.

Can you tell me your opinion about this results?

Thank you.

**Comment by sacmehta** [comment]
I am confused. Could you please clarify a bit more?

Did your changed increased the speed or decreased?

**Comment by userb2020** [comment]
Oh, my changed network's speed decreased.

**Comment by sacmehta** [comment]
This is obvious. Ideally, the change you made is inline with Gaussian kernel factorization trick and should improve the speed. However, you are creating two kernels. The cost of creating a kernel is more and hence reducing the inference time. Hope this helps.

**Comment by userb2020** [comment]
Ah, now I know the reason why I got low performance on inference speed. Thank you very much!
