### ISSUE TITLE
Training with my dataset using cityscapes pretrained weights. 

### ISSUE THREAD

**Issue by msson** [sacmehta/ESPNet#41]
Hi,

I would like to train ESPNet model with my dataset from Cityscapes pretrained weights that you uploaded on /pretrained/encoder/ folder, not from scratch.
Could you please give some advice how to do this?

Thanks.

**Comment by sacmehta** [comment]
You can load the pretrained model and replace the classification layer with the randomly initialized one. Then you should be good to train on your dataet.

Let me know if you have any specific questions.

**Comment by msson** [comment]
I can figure it out now thanks.

Do you also have pre-trained weights on the ImageNet?
I would like to try training the network with ImageNet pretrained weights data but I am not sure you have this one. (like you shared it on ESPNetv2) 

Thank you.

**Comment by sacmehta** [comment]
No, we didn’t train ESPNet on the ImageNet dataset.

**Comment by msson** [comment]
Thanks.
