### ISSUE TITLE
How to convert the label images to trainIDs using the cityscape scripts.

### ISSUE THREAD

**Issue by MrLinNing** [sacmehta/ESPNet#42]
Hello， @sacmehta 

I'm new learner in semantic segmentation.
My dataset structure is：
![image](https://user-images.githubusercontent.com/24288811/49365953-084d4d80-f723-11e8-9082-a69bd235b7a2.png)
![image](https://user-images.githubusercontent.com/24288811/49366264-dd172e00-f723-11e8-9b09-23b0a8fcec60.png)

Problem happened, when i run `python main.py` in the train folder.
```
Label Image ID: 
...
/home/ll/DATA/cityscapes/gtFine/train/zurich/zurich_000032_000019_gtFine_labelTrainIds.png
Labels can take value between 0 and number of classes.
Some problem with labels. Please check.
...
```
Can you help me? Thanks.

**Comment by sacmehta** [comment]
You need to create ground truth masks with trainIds first. Follow this file for conversion:

https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py

**Comment by MrLinNing** [comment]
Can you give me more details? I don't know how to operate it.
I think the ground truth masks with trainIds already created. 
![image](https://user-images.githubusercontent.com/24288811/49427682-eaddb980-f7de-11e8-8851-d08417004308.png)

**Comment by TianMingChen** [comment]
> Can you give me more details? I don't know how to operate it.
> I think the ground truth masks with trainIds already created.
> ![image](https://user-images.githubusercontent.com/24288811/49427682-eaddb980-f7de-11e8-8851-d08417004308.png)

hello,how do you to solve this problem?

**Comment by ccyy** [comment]
Hi, by using the below code, I could get color. png, how can I get labelids.png instead?
Shall I convert it, or just edit the below code?
https://www.kaggle.com/code/joechen02/pspnet-demo/comments
Thank you

**Comment by abheek19** [comment]
@sacmehta
 I have the images and labeled_images in png format. How do i convert the label images to trainIDs using cityscape scripts. I went to use the script but i could not get it working.
