### ISSUE TITLE
Difference between your paper and source code. 

### ISSUE THREAD

**Issue by msson** [sacmehta/ESPNet#43]
Hi,

During I check your codes, I found some different part between the paper and codes.

your paper mentioned, for the decoder part, output0_cat is applied by 1x1 conv (19,C) and then concat but I can see output0_cat does not pass 1x1 conv (19,C). 
Look at this part in your code which is Model.py (the last part of decoder)  

self.conv = CBR(19 + classes, classes, 3, 1)
concat_features = self.conv(torch.cat([comb_l2_l3, output0_cat], 1))

This shows that output0_cat + comb_l2_l3 passes CBR (19 + classes, classes, 3, 1) and it means output0_cat does not pass 1x1 conv (19,C).

I would like to know why there is the difference.

Thanks!

**Comment by sacmehta** [comment]
See #14 and #15

**Comment by msson** [comment]
@sacmehta Thank you.
