### ISSUE TITLE
Can you share the codes about train the camvid dataset ?

### ISSUE THREAD

**Issue by monk42** [sacmehta/ESPNet#45]
Can you share the codes about train the camvid dataset , or tell me how to preprocessing camvid dataset for training! 
    Thanks!

**Comment by pkuqgg** [comment]
> ```
>  Can you share the codes about train the camvid dataset , or tell me how to preprocessing camvid dataset for training! 
> Thanks!
> ```

Hello! Did you finally get codes for train the camvid dataset?

**Comment by sacmehta** [comment]
We used the same code and procedure for the Camvid dataset. Please change the loadData.py file for CamVid dataset and you should be good to go
