### ISSUE TITLE
Question about RuntimeError 

### ISSUE THREAD

**Issue by msson** [sacmehta/ESPNet#49]
Hi, 

I got this error when I try to train the model, could you give some advice? 

![2019-01-10 16-58-35](https://user-images.githubusercontent.com/35793913/50954223-1bf58c00-14f9-11e9-9e64-0ea3ff0d8e0f.png)

**Comment by sacmehta** [comment]
There is a mismatch in the output of ghe model and target (ground truth) dimensions. Please check

**Comment by msson** [comment]
@sacmehta Thanks.
