### ISSUE TITLE
Is this on purpose?myTransforms.Scale(1280, 720) not (1280,640)

### ISSUE THREAD

**Issue by wangyihuan123** [sacmehta/ESPNet#58]
Hi, 
I notice that the code below, and am wondering whether the scale 720  is on purpose (not 512*1.25)

train/main.py: https://github.com/sacmehta/ESPNet/blob/afe71c38edaee3514ca44e0adcafdf36109bf437/train/main.py#L227

trainDataset_scale2 = myTransforms.Compose([
        myTransforms.Normalize(mean=data['mean'], std=data['std']),
        myTransforms.Scale(1280, 720), # <<<<<<<<<< 512*1.25 == 640 ?
        myTransforms.RandomCropResize(100),
        myTransforms.RandomFlip(),
        #myTransforms.RandomCrop(64),
        myTransforms.ToTensor(args.scaleIn),
        #
])

**Comment by sacmehta** [comment]
There is no specific reason behind this choice. We just selected it to have 720p resolution.
