### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by KengChiLiu** [sacmehta/ESPNet#6]
Hi @sacmehta ,
How long did it take you to train the model ?
Training with different scales and 300 epoch (default setting) seems to take a long long time......

**Comment by sacmehta** [comment]
Training should be done in 2-3 days on TItanX PASCAL Single GPU.

Note that the Cityscape dataset has high resolution images (2048 x 1024). These images are large in comparison to other standard datasets such as the ImageNet and the PASCAL VOC.
