### ISSUE TITLE
Evaluate PASCAL VOC 2012 test set 

### ISSUE THREAD

**Issue by InstantWindy** [sacmehta/ESPNet#62]
Hi! How do you evaluate the VOC 2012 test set? How did you test the segmentation results of VOC2012 test data set on PASCAL VOC official website? Looking forward to your reply. Thanks!

**Comment by sacmehta** [comment]
This is a straight forward process. Generate the segmentation masks and resize them to the same size as of original input image using nearest neighbor interpolation and then color code them. Use the same class and color mapping as PASCAL does. See their official Matlab code for more details.

P.S.: Make sure that your results folder adhere to the same folder structure that PASCAl accepts.

**Comment by InstantWindy** [comment]
But I am a bit confused,The file structure described on the official website is as follows：
![image](https://user-images.githubusercontent.com/23608180/56107935-8f38ef00-5f7b-11e9-87c0-5ade46ed6dde.png)
But I only have segmentation results, no other results,for example, under Main, Layout and Action folders,
Do I need to upload these folders? Thanks!

**Comment by sacmehta** [comment]
You don’t need other folders.

**Comment by InstantWindy** [comment]
You mean that I only need to upload the "results/VOC2012/Segmentation" folder? Thanks!

**Comment by sacmehta** [comment]
You need to compress this folder and upload 

results/VOC2012/Segmentation/comp6_test_cls

**Comment by InstantWindy** [comment]
Yes, I understand . What is the difference between "results/VOC2012/Segmentation/comp6_test_cls" folder and "results/VOC2012/Segmentation/comp5_test_cls" folder?   They belong to segmentation. Thanks!

**Comment by sacmehta** [comment]
Well, you need to read the documentation on the PASCAL website for more details.

**Comment by victorbug** [comment]
For anyone else wondering, this information is in:

![image](https://user-images.githubusercontent.com/68400642/216753088-a65504df-a522-4a4a-96c2-1797affa78ef.png)
![image](https://user-images.githubusercontent.com/68400642/216753098-28051037-8784-4dce-8f64-af703af943fe.png)

http://host.robots.ox.ac.uk/pascal/VOC/voc2012/devkit_doc.pdf (link found in: http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html in "Development Kit" -->"Download the [PDF documentation] (500KB PDF)"
