### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by TianMingChen** [sacmehta/ESPNet#63]
When I run this"python VisualizeResults.py --modelType 1 --p 2 --q 3"，but it show "RuntimeError: CUDA error: out of memory"，what should i do?

**Comment by sacmehta** [comment]
How much memory does your GPU have?

**Comment by TianMingChen** [comment]
![图片](https://user-images.githubusercontent.com/20785298/56285525-01f7c500-614a-11e9-9c84-aa4ef3b6b196.png)

**Comment by TianMingChen** [comment]
> 
> 
> How much memory does your GPU have?

it has been solved.

**Comment by TianMingChen** [comment]
> 
> 
> How much memory does your GPU have?

it has been solved.Thanks.
