### ISSUE TITLE
 how to convert the Cityscapes dataset to 19 categories. 

### ISSUE THREAD

**Issue by TianMingChen** [sacmehta/ESPNet#64]
Hi , I am new to segmentation field, and I meet the problem about how to convert the Cityscapes dataset to 19 categories. Look forward to your reply. Thank you !!

**Comment by sacmehta** [comment]
You need to follow the directions given on the Cityscapes repository.

See this file for more details:

https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py

**Comment by TianMingChen** [comment]
> You need to follow the directions given on the Cityscapes repository.
> 
> See this file for more details:
> 
> https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py

when I run main.py,how should I to deal this problem?
I have python createTrainIdLabelImgs.py
![image](https://user-images.githubusercontent.com/20785298/56499310-634bd980-6538-11e9-90e8-5114e073ade2.png)

![image](https://user-images.githubusercontent.com/20785298/56499291-53cc9080-6538-11e9-89c9-d54e42882ec6.png)

**Comment by sacmehta** [comment]
You have 255 value in your label files. Use this file from ESPNetv2.

https://github.com/sacmehta/ESPNetv2/blob/master/segmentation/loadData.py

**Comment by sacmehta** [comment]
Also, use this Dataset.py file

https://github.com/sacmehta/ESPNetv2/blob/master/segmentation/DataSet.py

**Comment by TianMingChen** [comment]
> Also, use this Dataset.py file
> 
> https://github.com/sacmehta/ESPNetv2/blob/master/segmentation/DataSet.py

I replace the two file ,but it still have such problem?
![image](https://user-images.githubusercontent.com/20785298/56500376-1ae2ea80-653d-11e9-89ed-d29dd73f68af.png)

**Comment by sacmehta** [comment]
You have 255 in labels. Please change loadData.py file as below.

Replace below code
```
unique_values = np.unique(label_img)
 # if you have 255 label in your label files, map it to the background class (19) in the Cityscapes dataset
if 255 in unique_values:
    label_img[label_img==255] = 19
```
with
```
unique_values = np.unique(label_img)
# if you have 255 label in your label files, map it to the background class (19) in the Cityscapes dataset
if 255 in unique_values:
	label_img[label_img==255] = 19
	unique_values = np.unique(label_img)
```

**Comment by TianMingChen** [comment]
> You have 255 in labels. Please change loadData.py file as below.
> 
> Replace below code
> 
> ```
> unique_values = np.unique(label_img)
>  # if you have 255 label in your label files, map it to the background class (19) in the Cityscapes dataset
> if 255 in unique_values:
>     label_img[label_img==255] = 19
> ```
> with
> 
> ```
> unique_values = np.unique(label_img)
> # if you have 255 label in your label files, map it to the background class (19) in the Cityscapes dataset
> if 255 in unique_values:
> 	label_img[label_img==255] = 19
> 	unique_values = np.unique(label_img)
> ```

OK,the problem has been solved!
Thank you !
And also when  PyTorch>=0.5, the index of 0-dim tensor is invalid. The master branch is designed for PyTorch 0.4.1, loss.data[0] works well.
Try to change  epoch_loss.append(loss.data[0])
to  epoch_loss.append(loss.data)

**Comment by sacmehta** [comment]
You should use loss.item() instead of loss.data for PyTorch version greater than 0.3

**Comment by TianMingChen** [comment]
> You should use loss.item() instead of loss.data for PyTorch version greater than 0.3

OK,thanks!
