### ISSUE TITLE
optimizer.zero_grad() 

### ISSUE THREAD

**Issue by erichhhhho** [sacmehta/ESPNet#68]
Hi,

I think you zero the grad two time during training. [Here](https://github.com/sacmehta/ESPNet/blob/master/train/main.py#L98) and [Here](https://github.com/sacmehta/ESPNet/blob/master/train/main.py#L101)

**Comment by sacmehta** [comment]
Thanks for noting it. You can remove one of them. It should not impact anything.

Also, if our work excites you, we have released a new repository. Have a look.

http://github.com/sacmehta/EdgeNets
