### ISSUE TITLE
Train dataset with more than 20 classes

### ISSUE THREAD

**Issue by rocklinsuv** [sacmehta/ESPNet#70]
Hi there,

Recently I have created my own dataset with more than 20 classes (around 26 perhaps) for landscape segmentation. It is possible to train this dataset with ESPNet? Some hints for code modification would be very much appreciated.
Another thing is that I previously labelled the images with Labelme, where background pixels are assigned with pixel value 0. Do I need to set them to max_class+1, or just simplely leave them as 0 and ignore them in training?
Thank you!

Best Regards,
Lyn

**Comment by sacmehta** [comment]
We provided a custom dataset loader script here:

https://github.com/sacmehta/EdgeNets/blob/33feca9ab65c29ac295daae72401681a80fa8c01/data_loader/segmentation/custom_dataset_loader.py#L20

See if it helps. Sorry for late response.

**Comment by rocklinsuv** [comment]
Thank you for your reply. Haven't been here for a while. I came up with a solution which loops through all the image pixels and subtract each pixel value by 1, then set all those -1 pixels (background) to 255. Now I simply train ESPNet with --classes=n+1. Please let me know if I'm doing the right thing since the custom_datset_loader you provided need to be modified a lot. Thanks!
