### ISSUE TITLE
Size mismatch issue while testing retrained ESPNet on Cityscapes

### ISSUE THREAD

**Issue by prajakta-13** [sacmehta/ESPNet#73]
Hi Sachin,
Thank you for your work!
I am trying to use the repo and retrain ESPNet on Cityscapes. I have generated a decoder model and while trying to generate inference on the same, I am facing a runtime error depicting size mismatch.

size mismatch for conv.conv.weight: copying a param of torch.Size([20, 36, 3, 3]) from checkpoint, where the shape is torch.Size([20, 39, 3, 3]) in current model.

Can you please let me know what might be going wrong here?

Thanks in advance!
_Prajakta Kulkarni

**Comment by sacmehta** [comment]
See https://github.com/sacmehta/ESPNet/issues/14
