### ISSUE TITLE
Exact versions of all the packages

### ISSUE THREAD

**Issue by NadeemAtif-Alig** [sacmehta/ESPNet#79]
Hey Sachin, thanks a lot for sharing this code of ESPNet. You must be aware that how difficuilt it is to lay down the correct platform to make the code run. Giving the code the required environment is almost half the work done. Can you please share the exact versions of different packages used in this project. Thanks in advance.

**Comment by sacmehta** [comment]
These are the packages that are required for this codebase:

https://github.com/sacmehta/ESPNet#pre-requisite

The main dependency is the PyTorch. This code was written 3 years back, and back then PyTorch version is `0.3.0`. You would have noticed it if you spent a minute reading the documentation, and actually interested in learning about the code. Anyways, with few modifications, you should be able to use it with the latest PyTorch version. Several people in the community have reproduced our results successfully (including TensorFlow), so I believe there is no issue with the documentation and code. 

Please read more about using old versions here:

https://pytorch.org/get-started/previous-versions/
